### ISSUE TITLE
Bug: Block of Valkyrum and Pyral don't drop the item when mined

### ISSUE THREAD

**Issue by SimulationOfMario** [The-Aether-Team/Treasure-Reforging#2]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.3.5

### Treasure Reforging Version

1.0.0

### Is This Bug a Conflict With Another Mod?

No

### Steps to Reproduce

1. Mine a Valkyrum/Pyral block
2. The block breaks but doesn't drop its item

### What You Expect To Happen

That the block item appears because otherwise it is lost.

### What Actually Happened

The block does not drop its item.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Fixed in the latest hotfix
